#!/usr/bin/python

import os
import sys
import time
import urllib2
import json
from pprint import pprint

# https://api.blocktrail.com/v1/bcc/address/XXX?api_key=MY_APIKEY

bcc_address = 'XXX'
api_key = 'XXX'
api_secret = 'XXX'

blocktrail_url = 'https://api.blocktrail.com/v1/bcc/address/' + bcc_address + '?api_key=' + api_key

hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}


if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title current BCH balance on wallet"
	print "graph_vlabel BCH"
	print "graph_category accounting"
	print "graph_printf %#.4lf"
	print "graph_scale no"
	print "graph_args --left-axis-format %#.3lf"
	print "graph_info current BCH balance on wallet"
        print "balance.info current BCH balance on wallet"
        print "balance.label balance"
	quit()


# get the current BCH balance from blockchain.info

req = urllib2.Request(blocktrail_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)


current_balance = float(data['balance']) / 100000000


# print the balance

print "balance.value %s" % (current_balance)

