#!/usr/bin/python

import os
import sys
import time
import urllib2
import json
from pprint import pprint

api_key = 'XXX';

bittrex_url = 'https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=BTC-BCC&tickInterval=thirtyMin&_' + str(time.time())


if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title current BCC balance on pool.bitcoin.com in BTC"
	print "graph_vlabel BTC"
	print "graph_category accounting"
	print "graph_printf %#.4lf"
	print "graph_scale no"
	print "graph_args --left-axis-format %#.3lf"
	print "graph_info current BCC balance on pool.bitcoin.com in BTC"
        print "balance.info current BCC balance on pool.bitcoin.com in BTC"
        print "balance.label balance"
	quit()



# https://console.pool.bitcoin.com/srv/api/user?apikey=XXX

pool_url = 'https://console.pool.bitcoin.com/srv/api/user?apikey=' + api_key;

hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}


# get the BCC balance from the pool

req = urllib2.Request(pool_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)

current_balance = float(data['bitcoinCashBalance'])


# get the price of BCC from bittrex

req = urllib2.Request(bittrex_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)

btc_usd = float(data['result'][0]['C'])


# print the result

print "balance.value %s" % (current_balance * btc_usd)

