#!/usr/bin/python

import os
import sys
import time
import urllib2
import json
from pprint import pprint

# http://1.2.3.4:9880/wallet

sia_url = 'http://1.2.3.4:9880/wallet'

hdr = {'User-Agent': 'Sia-Agent',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}


if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title current SC balance on wallet"
	print "graph_vlabel SC"
	print "graph_category accounting"
	print "graph_printf %#.4lf"
	print "graph_scale no"
	print "graph_args --left-axis-format %#.3lf"
	print "graph_info current SC balance on wallet"
        print "balance.info current SC balance on wallet"
        print "balance.label balance"
	quit()


# get the current BCH balance from blockchain.info

req = urllib2.Request(sia_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)


current_balance = float(data['confirmedsiacoinbalance']) / 1000000000000000000000000


# print the balance

print "balance.value %s" % (current_balance)

