#!/usr/bin/python

import os
import sys
import time
import hashlib
import hmac
import urllib2
import json
from pprint import pprint

# https://antpool.com/api/account.htm?key=XXX&nonce=YYY&signature=ZZZ&coin=COIN

user_id = 'XXX'
api_key = 'YYY'
secret_key = 'ZZZ'
coin_name = 'SC'
nonce = str(time.time())

bittrex_url = 'https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=BTC-SC&tickInterval=thirtyMin&_' + nonce


hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}


if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title current SC balance on antpool in BTC"
	print "graph_vlabel BTC"
	print "graph_category accounting"
	print "graph_printf %#.4lf"
	print "graph_scale no"
	print "graph_args --left-axis-format %#.3lf"
	print "graph_info current SC balance on antpool in BTC"
        print "balance.info current SC balance on antpool in BTC"
        print "balance.label balance"
	quit()


# get the current SC balance from antpool

message = user_id + api_key + nonce
signature = hmac.new(secret_key, msg=message, digestmod=hashlib.sha256).hexdigest().upper()

antpool_url = 'https://antpool.com/api/account.htm?key=' + api_key + '&nonce=' + nonce + '&signature=' + signature + '&coin=' + coin_name;


req = urllib2.Request(antpool_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)

current_balance = float(data['data']['balance'])


# get the price of SC from bittrex

req = urllib2.Request(bittrex_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)

btc_sc = float(data['result'][0]['C'])


# print the result

print "balance.value %s" % (current_balance * btc_sc)

