#!/usr/bin/python

import os
import sys
import time
import hashlib
import hmac
import urllib2
import json
from pprint import pprint

# http://sia.luxor.tech/api/user/XXX

sia_address = 'XXX'
nonce = str(time.time())

hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}


if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title current SC balance on luxor in USD"
	print "graph_vlabel USD"
	print "graph_category accounting"
	print "graph_printf %#.4lf"
	print "graph_scale no"
	print "graph_args --left-axis-format %#.3lf"
	print "graph_info current SC balance on luxor in USD"
        print "balance.info current SC balance on luxor in USD"
        print "balance.label balance"
	quit()


# get the current SC balance from luxor

luxor_url = 'http://sia.luxor.tech/api/user/' + sia_address


req = urllib2.Request(luxor_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)

# for some reason the balance is provided with an 1e+24 multiplier

current_balance = float(data['balance']) / 1e+24

print current_balance


# get the price of SC from bittrex in BTC

bittrex_url = 'https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=BTC-SC&tickInterval=thirtyMin&_' + nonce

req = urllib2.Request(bittrex_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)

btc_sc = float(data['result'][0]['C'])


# get the price of BTC from bittrex in USD

bittrex_url = 'https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=USDT-BTC&tickInterval=thirtyMin&_' + nonce

req = urllib2.Request(bittrex_url, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)

btc_usd = float(data['result'][0]['C'])


# print the result

print "balance.value %s" % (current_balance * btc_sc * btc_usd)

