#!/usr/bin/python

import os
import sys
import time
from pprint import pprint
import rrdtool


plugin_field_data = os.path.basename(sys.argv[0]).split('change_since_yesterday_')[1];

rrd_base_path = "/var/lib/munin/XXX/YYY.ZZZ-" + plugin_field_data + "-g.rrd"


if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title change since yesterday for %s" % (plugin_field_data)
	print "graph_vlabel USD"
	print "graph_category mining"
	print "graph_printf %#.4lf"
	print "graph_scale no"
	print "graph_args --left-axis-format %#.3lf"
	print "graph_info change since yesterday for %s" % (plugin_field_data)
        print "change_since_yesterday.info change since yesterday for %s" % (plugin_field_data)
        print "change_since_yesterday.label change"
	quit()


# get the value from 1 day ago

result = rrdtool.fetch(rrd_base_path, "LAST", "-a", "-r", "5m", "-s", "-1d", "-e", "-1d");
#start, end, step = result[0]
#ds = result[1]
rows = result[2]
value_one_day_ago = rows[0][0];

print value_one_day_ago;

# get the value for now / last measured

result = rrdtool.fetch(rrd_base_path, "LAST", "-a", "-r", "5m", "-s", "-10m", "-e", "-10m");
#start, end, step = result[0]
#ds = result[1]
rows = result[2]
value_now = rows[0][0];

print value_now;

print "change_since_yesterday.value %s" % (float(value_now - value_one_day_ago));


