#!/usr/bin/python

import sys
import socket
import json
from pprint import pprint

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM);
s.connect(("localhost", 3333));
s.send('{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}');
response = s.recv(1024);
s.close();

data = json.loads(response);

per_gpu_data = data['result'][3].split(";");

if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title Claymore mining speed per GPU"
	print "graph_args -l 0"
	print "graph_vlabel H/s"
	print "graph_category mining"
	print "graph_info Claymore ETH mining performance per GPU"

        for gpu_id in range(0, len(per_gpu_data)):
		print "speed_hps%s.info Mining speed for GPU %s" % (gpu_id, gpu_id)
		print "speed_hps%s.label GPU %s" % (gpu_id, gpu_id)

	quit()

for gpu_id in range(0, len(per_gpu_data)):
    print "speed_hps%s.value %s" % (gpu_id, float(per_gpu_data[gpu_id]))


