#!/usr/bin/python

import sys
import urllib2
import json
from pprint import pprint

stat = urllib2.urlopen("http://127.0.0.1:42000/getstat").read()
data = json.loads(stat)

if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title EWBF mining speed per GPU"
	print "graph_vlabel Sol/s"
	print "graph_category mining"
	print "graph_info EWBF ZEC mining performance per GPU"

	for gpu in data['result']:
		print "speed_sps%s.info Mining speed for GPU %s: %s" % (gpu['cudaid'], gpu['cudaid'], gpu['name'])
		print "speed_sps%s.label GPU %s: %s" % (gpu['cudaid'], gpu['cudaid'], gpu['name'])

	quit()

for gpu in data['result']:
	print "speed_sps%s.value %s" % (gpu['cudaid'], gpu['speed_sps'])


