#!/usr/bin/python

import os
import sys
import urllib2
import json
from pprint import pprint

requested_coin = os.path.basename(sys.argv[0]).split('_')[-1];

# https://[coin_name.]miningpoolhub.com/index.php?page=api&action=<method>&api_key=<user_api_key>[&<argument>=<value>]

api_key = 'XXX'
user_id = 'XXX'
coin_name = requested_coin
action = 'getdashboarddata'

url_base = 'https://' + coin_name + '.miningpoolhub.com/index.php?page=api' + '&action=' + action + '&api_key=' + api_key + '&id=' + user_id;

hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}

req = urllib2.Request(url_base, headers=hdr)
resp = urllib2.urlopen(req)
stat = resp.read()
data = json.loads(stat)



if (len(sys.argv) > 1) and (sys.argv[1] == "config") :
	print "graph_title " + data['getdashboarddata']['data']['pool']['info']['name']
	print "graph_vlabel " + data['getdashboarddata']['data']['pool']['info']['currency']
	print "graph_category mining"
	print "graph_info " + data['getdashboarddata']['data']['pool']['info']['name']
        print "recent_credits_24hours.info Credits in the last 24 hours"
        print "recent_credits_24hours.label Amount"
	quit()

recent_credits_24hours = float(data['getdashboarddata']['data']['recent_credits_24hours']['amount'])

print "recent_credits_24hours.value %s" % (recent_credits_24hours)


